### ISSUE TITLE
I2C, wrong address for ER-301

### ISSUE THREAD

**Issue by Elberstein** [16n-faderbank/16n#13]
The i2C address 0xB0 is no longer used by the ER-301.

```
      // ER-301
      sendi2c(0xB0, 0, 0x11, q, notShiftyTemp);
```

The new address should be 0x31 or 0x32 or 0x33

```
  // ER-301
  sendi2c(0x31, 0, 0x11, q, notShiftyTemp);
```

**Comment by infovore** [comment]
`master` branch is now up-to-date with correct addresses.
