### ISSUE TITLE
16n not recognized by other midi interfaces (Hermod, IconnectMidi 4+)

### ISSUE THREAD

**Issue by Elberstein** [16n-faderbank/16n#21]
The 16n plugged via USB is recognized by my Mac but it is not recognized by other MIDI interfaces like Hermod and IconnectMidi 4+ (plugged into their respective "USB hosts" ports) Do you think it can be fixed ?

**Comment by Elberstein** [comment]
The 16n is now recognized by IconnectMIdi4+ after recompiling for MIDI and not SERIAL + MIDI

**Comment by infovore** [comment]
Glad you got this solved.
