### ISSUE TITLE
Slide Pots - 10K?

### ISSUE THREAD

**Issue by okyeron** [16n-faderbank/16n#5]
BOM is not specific on value for slide pots.

Mouser lists 2 versions of the RS6011SP600x - RS6011SP6003 (10KOhms) and RS6011SP6004 (20Kohms)

Datasheet says the 10K RS6011SP6003 is 1B taper (linear) so I assume this is the right one. Might be good to update the BOM with that part number?

**Comment by infovore** [comment]
Octopart BOM - https://octopart.com/bom-tool/unJxkzvR - is specific and specifies 6003 (10k) parts.

However, technically, resistance doesn't matter that much as it's just being used as a voltage divider. Taper is, however, critical, and should be linear. I'll update `bom.csv` with the 6003 part though.
