### ISSUE TITLE
negative 5v

### ISSUE THREAD

**Issue by nemoy** [16n-faderbank/16n#53]
this isn't really an Issue, rather an idea.
many Eurorack Modules use + / - 5v control voltages.
Is there a possibility to send negative 5v out?

**Comment by infovore** [comment]
Not without changing the circuitry:

* the 5V source coming in is from the USB +5V line
* this is what the faders divide down, entirely in the analog domain, to output from the jacks. If you wanted them to output -5V, you'd have to find a way of getting a -5V reference into the fader input...
* ...but that fader output is _also_ sent through the opamps to be divided down to 3.3V levels to go into the Teensy. We can't feed negative voltages into those ADCs.

There are 16n variants that support wider voltage ranges - 0-5, 0-10V, and -5V-5V - I believe the Tesseract Modular "Sweet 16n" does. Michigan Synthworks XVI, which is not compatible with 16n firmware, but certainly inspired by it, also has a more flexible range of voltages.

Of course, if you wanted to modify the electronics to do so, you'd be welcome to work on your own derivative or related projects. To do it whilst still only using USB +5V in requires some boost conversion, I'd imagine.
