### ISSUE TITLE
Multiplexer missing from CSV BOM and Octopart BOM

### ISSUE THREAD

**Issue by infovore** [16n-faderbank/16n#6]
...and if it is, does that mean cap counts are correct too? Double check.

**Comment by infovore** [comment]
Nope - turns out the _wrong_ Octopart BOM was linked up. Fixed, now.

**Comment by Elberstein** [comment]
BOM.csv should be modified, it still lists CD74HC4067SM96 as multiplexer but it's the wrong package. It should be CD74HC4067M
